CREATE TABLE IF NOT EXISTS %schema%.users (
  id SERIAL PRIMARY KEY,
  handle VARCHAR NOT NULL,
  full_name VARCHAR NOT NULL,
  password VARCHAR NOT NULL,
  created TIMESTAMP WITH TIME ZONE NOT NULL,
  modified TIMESTAMP WITH TIME ZONE NOT NULL,
  meta JSON
);

CREATE TABLE IF NOT EXISTS %schema%.roles (
  id SERIAL PRIMARY KEY,
  name VARCHAR NOT NULL,
  title VARCHAR,
  description VARCHAR,
  created TIMESTAMP WITH TIME ZONE NOT NULL,
  modified TIMESTAMP WITH TIME ZONE NOT NULL,
  meta JSON
);

CREATE TABLE IF NOT EXISTS %schema%.user_roles (
  user_id INTEGER REFERENCES %schema%.users(id) ON DELETE CASCADE,
  role_id INTEGER REFERENCES %schema%.roles(id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, role_id)
);

